name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install rust (for docwen)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install docwen
      run: cargo install --git https://github.com/ErikSeewald/docwen --force

    - name: docwen check
      run: docwen check

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          libgl1-mesa-dev \
          libglew-dev \
          freeglut3-dev \
          libglfw3-dev \
          libglfw3 \
          libreadline-dev \
          libglm-dev \
          pkg-config \
          unzip

    - name: Download third-party dependencies
      run: |
        mkdir -p dependencies

        # Download tinyobjloader v1.0.6
        curl -L https://raw.githubusercontent.com/tinyobjloader/tinyobjloader/v1.0.6/tiny_obj_loader.h \
          -o dependencies/tiny_obj_loader.h

        # Download nlohmann-json v3.11.3
        curl -L https://raw.githubusercontent.com/nlohmann/json/v3.11.3/single_include/nlohmann/json.hpp \
          -o dependencies/json.hpp

        # Download ImGui 1.90.4 and unpack it
        curl -L https://github.com/ocornut/imgui/archive/refs/tags/v1.90.4.tar.gz | tar xz
        mv imgui-1.90.4 dependencies/imgui


    - name: Configure CMake
      working-directory: build
      run: cmake -S . -B linux

    - name: Build
      working-directory: build
      run: cmake --build linux
