name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          libgl1-mesa-dev \
          libglew-dev \
          freeglut3-dev \
          libglfw3-dev \
          libglfw3 \
          libreadline-dev \
          pkg-config

    - name: Configure CMake
      working-directory: Eriks_Wasp_Sim/build/cmake
      run: cmake -S . -B build

    - name: Build
      working-directory: Eriks_Wasp_Sim/build/cmake
      run: cmake --build build
